#!/bin/bash

if [ `pidof -s -x lcdcontrol` ] ; then
    kill `pidof -x lcdcontrol` 2> /dev/null
    kill -9 `pidof -x lcdcontrol` 2> /dev/null    
else
    echo "LCD control client isn't currently running"
fi
